name: 'Publish'
on:
    push:
        tags:
            - '*'
    pull_request:
        tags:
            - '*'
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Install and Build
              run: |
                npm ci
                npm run build --if-present
            - name: Publish
              with:
                  registry-url: https://npm.pkg.github.com/
              run: npm publish
